import json
from fastapi import FastAPI, Depends, HTTPException

from schemas import RegisterRequest, LoginRequest
from fastapi.middleware.cors import CORSMiddleware

from interview_agent import InterviewAgent
from voice_routes import router as voice_router

from sqlalchemy.orm import Session
from database import Base, engine
from models import User, InterviewResult
from auth import (
    get_db,
    hash_password,
    verify_password,
    create_access_token,
    get_current_user
)


app = FastAPI()
Base.metadata.create_all(bind=engine)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

Base.metadata.create_all(bind=engine)

app.include_router(voice_router)

agent = InterviewAgent(
    company="Product Based",
    role="Software Engineer",
    level="Intermediate"
)

@app.post("/interview/hr")
def hr_interview(answer: str):
    response = agent.hr_interviewer(answer)
    return {"question": response}

@app.post("/interview/tech")
def tech_interview(answer: str):
    response = agent.tech_interviewer(answer)
    return {"question": response}


# Authentication routes

@app.post("/auth/register")
def register(data: RegisterRequest, db: Session = Depends(get_db)):
    if db.query(User).filter(User.email == data.email).first():
        raise HTTPException(status_code=400, detail="Email already exists")

    user = User(
        name=data.name,
        email=data.email,
        password=hash_password(data.password)
    )
    db.add(user)
    db.commit()
    return {"message": "User registered successfully"}


@app.post("/auth/login")
def login(data: LoginRequest, db: Session = Depends(get_db)):
    user = db.query(User).filter(User.email == data.email).first()

    if not user or not verify_password(data.password, user.password):
        raise HTTPException(status_code=401, detail="Invalid credentials")

    token = create_access_token({"user_id": user.id})
    return {"access_token": token, "token_type": "bearer"}


@app.get("/auth/me")
def me(current_user: User = Depends(get_current_user)):
    return {
        "id": current_user.id,
        "name": current_user.name,
        "email": current_user.email
    }

#stop end point

@app.post("/interview/stop")
def stop_interview():
    # Only stop interview, DO NOT generate feedback here
    return {"message": "Interview stopped"}


#interview feedback

@app.post("/interview/feedback")
def interview_feedback(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    raw_feedback = agent.generate_feedback()

    # ✅ Convert JSON string → Python dict
    try:
        feedback = json.loads(raw_feedback)
    except Exception:
        raise HTTPException(
            status_code=500,
            detail="Invalid feedback format generated by AI"
        )

    result = InterviewResult(
        user_id=current_user.id,
        communication=int(feedback["communication"]),
        confidence=int(feedback["confidence"]),
        technical=int(feedback["technical"]),
        grammar=int(feedback["grammar"]),
        overall=int(feedback["overall"]),
        summary=feedback["summary"]
    )

    db.add(result)
    db.commit()

    # ✅ Clear interview history AFTER saving
    agent.history = []

    return {"feedback": feedback}

#interview history endpoint

@app.get("/interview/history")
def interview_history(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    results = (
        db.query(InterviewResult)
        .filter(InterviewResult.user_id == current_user.id)
        .order_by(InterviewResult.created_at.desc())
        .all()
    )

    return results
